version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node_api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build:
      context: ./frontend/task-net-frontend
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
